name: Test

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  test-build:
    name: Test and build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.23'

      - name: Go test
        run: 'go test ./...'

      - name: Static check
        uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"

      - name: Build # check if it builds
        run: go build
