name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger this workflow when a new tag is pushed that matches the pattern

jobs:
  build:
    name: Build and release Go binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23'

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build the Go binary
        run: |
          mkdir -p build
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags="-X 'main.Version=${{ env.VERSION }}'" -o bin/avdcli-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: avdcli-${{ matrix.goos }}-${{ matrix.goarch }}
          path: bin/avdcli-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/avdcli-linux-amd64
            bin/avdcli-linux-arm64
            bin/avdcli-darwin-amd64
            bin/avdcli-darwin-arm64
            bin/avdcli-windows-amd64
            bin/avdcli-windows-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
